server:
  port: 8500

spring:
  application:
    name: consumer_service

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka #eureka服务器地址