server:
  port: 7400

spring:
  application:
    name: product-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka #eureka服务器地址